name: Deploy to OVH (static)

on:
  push:
    branches: [ "main", "stage" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to PROD (/www) when on main
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.OVH_FTP_HOST }}
          username: ${{ secrets.OVH_FTP_USER }}
          password: ${{ secrets.OVH_FTP_PASS }}
          protocol: ftp
          port: 21
          security: loose
          local-dir: ./
          server-dir: /www/
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.github/**

      - name: Deploy to STAGE (/www/stage) when on stage
        if: ${{ github.ref == 'refs/heads/stage' }}
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.OVH_FTP_HOST }}
          username: ${{ secrets.OVH_FTP_USER }}
          password: ${{ secrets.OVH_FTP_PASS }}
          protocol: ftp
          port: 21
          security: loose
          local-dir: ./
          server-dir: /www/stage/
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.github/**
